In [1]:
!pip install pandas openpyxl plotly matplotlib seaborn

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

In [3]:
from google.colab import files

uploaded = files.upload()

Saving ApexPlanet_DataAnalytics_Dataset.xlsx to ApexPlanet_DataAnalytics_Dataset.xlsx

In [4]:
df = pd.read_excel("ApexPlanet_DataAnalytics_Dataset.xlsx")

df.head()

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [5]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.info()

Rows: 1000
Columns: 12
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

In [6]:
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Customer_Name     0
Age              20
Gender            0
City             13
Product           0
Category          0
Quantity          0
Unit_Price        0
Total_Sales       0
dtype: int64

In [7]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [8]:
df.drop_duplicates(inplace=True)

df.fillna(0, inplace=True)

In [10]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

df['Month'] = df['Order_Date'].dt.month_name()

In [11]:
total_revenue = df['Total_Sales'].sum()

total_orders = df['Order_ID'].nunique()

total_customers = df['Customer_ID'].nunique()

avg_order_value = total_revenue / total_orders

total_quantity = df['Quantity'].sum()

print("Total Revenue:", round(total_revenue,2))
print("Total Orders:", total_orders)
print("Total Customers:", total_customers)
print("Average Order Value:", round(avg_order_value,2))
print("Total Quantity Sold:", total_quantity)

Total Revenue: 139399439.65
Total Orders: 992
Total Customers: 947
Average Order Value: 140523.63
Total Quantity Sold: 5435

In [12]:
monthly_sales = df.groupby('Month')['Total_Sales'].sum().reset_index()

fig = px.bar(
    monthly_sales,
    x='Month',
    y='Total_Sales',
    title='Monthly Sales Trend'
)

fig.show()

In [13]:
category_sales = df.groupby('Category')['Total_Sales'].sum().reset_index()

fig = px.pie(
    category_sales,
    names='Category',
    values='Total_Sales',
    title='Category Contribution'
)

fig.show()

In [14]:
product_sales = df.groupby(
    'Product'
)['Total_Sales'].sum().reset_index()

product_sales = product_sales.sort_values(
    by='Total_Sales',
    ascending=False
).head(10)

fig = px.bar(
    product_sales,
    x='Product',
    y='Total_Sales',
    title='Top 10 Products'
)

fig.show()

In [15]:
city_sales = df.groupby(
    'City'
)['Total_Sales'].sum().reset_index()

city_sales = city_sales.sort_values(
    by='Total_Sales',
    ascending=False
).head(10)

fig = px.bar(
    city_sales,
    x='City',
    y='Total_Sales',
    title='Top Cities by Revenue'
)

fig.show()

In [16]:
customer_sales = df.groupby(
    ['Customer_ID','Customer_Name']
)['Total_Sales'].sum().reset_index()

def segment(x):
    if x > 150000:
        return "High Value"
    elif x > 75000:
        return "Medium Value"
    else:
        return "Low Value"

customer_sales['Segment'] = customer_sales[
    'Total_Sales'
].apply(segment)

customer_sales.head()

  Customer_ID Customer_Name  Total_Sales       Segment
0    CUST1004  Customer_191      8321.54     Low Value
1    CUST1017  Customer_387    264230.68    High Value
2    CUST1026  Customer_445    164965.29    High Value
3    CUST1032   Customer_20    146990.90  Medium Value
4    CUST1038  Customer_454     37068.40     Low Value

In [17]:
fig = px.pie(
    customer_sales,
    names='Segment',
    title='Customer Segmentation'
)

fig.show()

In [18]:
gender_sales = df.groupby(
    'Gender'
)['Total_Sales'].sum().reset_index()

fig = px.bar(
    gender_sales,
    x='Gender',
    y='Total_Sales',
    title='Sales by Gender'
)

fig.show()

In [19]:
fig = px.histogram(
    df,
    x='Age',
    title='Customer Age Distribution'
)

fig.show()

In [20]:
print("KEY INSIGHTS")

print("1. Certain product categories contribute most revenue.")
print("2. Top customers generate significant sales.")
print("3. Revenue varies across cities.")
print("4. Age influences purchasing behavior.")
print("5. Monthly trends reveal seasonal demand.")

KEY INSIGHTS
1. Certain product categories contribute most revenue.
2. Top customers generate significant sales.
3. Revenue varies across cities.
4. Age influences purchasing behavior.
5. Monthly trends reveal seasonal demand.